# Generated by Django 3.0.6 on 2021-03-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyorrent', '0002_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
