# Generated by Django 3.0.6 on 2021-03-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyorrent', '0003_scenario_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
