# Generated by Django 3.0.6 on 2021-04-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyorrent', '0007_scenario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
