# Generated by Django 3.0.6 on 2021-04-01 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyorrent', '0008_delete_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('houseprice', models.DecimalField(decimal_places=0, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=0, max_digits=8)),
                ('interest_rate', models.DecimalField(decimal_places=0, max_digits=8)),
                ('buildingfees', models.DecimalField(decimal_places=0, max_digits=8)),
                ('maintenancecosts', models.DecimalField(decimal_places=0, max_digits=8)),
                ('rent', models.DecimalField(decimal_places=0, max_digits=8)),
                ('rentersinsurance', models.DecimalField(decimal_places=0, max_digits=8)),
                ('inflation', models.DecimalField(decimal_places=0, max_digits=8)),
                ('growth_ftse', models.DecimalField(decimal_places=0, max_digits=8)),
                ('growth_house', models.DecimalField(decimal_places=0, max_digits=8)),
                ('summary', models.CharField(max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
