# Generated by Django 3.0.6 on 2021-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyorrent', '0009_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='houseprice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
